#!/bin/bash
### BEGIN INIT INFO
# Provides: servicioweb
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start or stop the daemon.
# Description: Miniservidor web en python
### END INIT INFO

DIR=/home/pi/web
USER=pi
PROGRAM=servidor_web.py
DEBUGFILE=/home/pi/web/root/pypa_debug.log
PIDFILE=/home/pi/web/pid


start()
{
	echo "Iniciando servicio..."
	if [ -s $PIDFILE ]
	then
		rm $PIDFILE 2> /dev/null
	fi
	start-stop-daemon --start --chuid $USER --chdir $DIR -b --no-close -m --pidfile $PIDFILE --exec $PROGRAM 2>> $DEBUGFILE
	echo PID `cat $PIDFILE`
	echo "Servicio iniciado"
}

stop()
{
	echo "Parando servicio..."
	echo PID `cat $PIDFILE`
	start-stop-daemon --stop --pidfile $PIDFILE
	echo "Servicio parado"
	rm $PIDFILE 2> /dev/null
	killall -u pi -s 9 dbus-daemon
}

status()
{
	start-stop-daemon --status --pidfile $PIDFILE
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status
		;;
	*)
		echo "Uso: service servicioweb (start|stop|restart|status)"
		exit 1
		;;
esac

exit

